Commenting out cleanup for now

diff --git a/.github/workflows/build-test-and-deploy.yml b/.github/workflows/build-test-and-deploy.yml
--- a/.github/workflows/build-test-and-deploy.yml
+++ b/.github/workflows/build-test-and-deploy.yml
@@ -1033,39 +1033,32 @@ jobs:
           path: tests/playwright-report/
           retention-days: 30
 
-  cleanup:
-    name: "Cleanup images"
-    runs-on: ubuntu-latest
-    needs:
-      - end-to-end-tests
-      - prod-single-domain-deploy-tests
-      - helm-test
-    if: always()
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-
-      - name: Login to DockerHub
-        uses: docker/login-action@v3
-        if: ${{ github.event_name == 'push' || github.event_name == 'release' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]') }}
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
-
-      - name: Login to GHCR
-        uses: docker/login-action@v3
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Delete amd64 and arm64 tags from DockerHub
-        run: |
-          docker rmi thecodingmachine/workadventure-play:amd64-${{ github.sha }}
-          docker rmi thecodingmachine/workadventure-play:arm64-${{ github.sha }}
-
-      - name: Delete amd64 and arm64 tags from GHCR
-        run: |
-          docker rmi ghcr.io/workadventure/play:amd64-${{ github.sha }}
-          docker rmi ghcr.io/workadventure/play:arm64-${{ github.sha }}
-
+#  cleanup:
+#    name: "Cleanup images"
+#    runs-on: ubuntu-latest
+#    needs:
+#      - end-to-end-tests
+#      - prod-single-domain-deploy-tests
+#      - helm-test
+#    if: always()
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@v2
+#
+#      - name: Login to DockerHub
+#        uses: docker/login-action@v3
+#        if: ${{ github.event_name == 'push' || github.event_name == 'release' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]') }}
+#        with:
+#          username: ${{ secrets.DOCKER_USERNAME }}
+#          password: ${{ secrets.DOCKER_PASSWORD }}
+#
+#      - name: Login to GHCR
+#        uses: docker/login-action@v3
+#        with:
+#          registry: ghcr.io
+#          username: ${{ github.actor }}
+#          password: ${{ secrets.GITHUB_TOKEN }}
+#
+#      - name: Delete amd64 and arm64 tags
+#        run: |
+#          TODO: maybe use https://micro.webology.dev/2024/04/23/github-actions-cleaning.html ?
